SECTION TEXT
INPUT OLD_DATA
LOAD OLD_DATA
L1: DIV DOIS
STORE NEW_DATA
MULT DOIS
STORE TMP_DATA
LOAD OLD_DATA+2
SUB TMP_DATA
OUTPUT TMP_DATA
COPY NEW_DATA,OLD_DATA
LOAD OLD_DATA
JMPP L1
STOP
SECTION DATA
DOIS: CONST 2
LETRA: CONST "A"
OLD_DATA: SPACE 3
NEW_DATA: SPACE
TMP_DATA: SPACE
CHAR: SPACE
STRING: SPACE 5